config/routes.rb
Rails.application.routes.draw do
  resources :missions do
    resources :squads do
      resources :crews
    end
  end
  devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :droids
  resources :ships
  resources :locations
  resources :users, except: [:destroy]
  root to: "missions#index"
  
  get "/error404", to: "static_pages#error404"
  get "/error401", to: "static_pages#error401"
end

app/models/crew.rb
class Crew < ApplicationRecord
  validates :name,  presence: true
  has_and_belongs_to_many :droids
  has_and_belongs_to_many :rebels, class_name: "User", join_table: :crews_rebels
  has_and_belongs_to_many :passengers, class_name: "User", join_table: :crews_passengers
  
  belongs_to :ship  
  belongs_to :squad

  validates_presence_of :droids, :rebels, :ship
  
end

app/controllers/crews_controller.rb
class CrewsController < ApplicationController
  before_action :set_mission
  before_action :set_squad
  before_action :set_crew, only: %i[ show edit update destroy ]

  # GET /missions/:mission_id/squads/:squads_id/crews or /missions/:mission_id/squads/:squads_id/crews.json
  def index
    if @squad.nil?
      render "static_pages/error404", status: :not_found
    else
      @crews = @squad.crews
    end
  end

  # GET /missions/:mission_id/squads/:squads_id/crews/1 or /missions/:mission_id/squads/:squads_id/crews/1.json
  def show
    render "static_pages/error404", status: :not_found unless current_user && 
    (current_user.admin || @crew.id.in?(@squad.crews.ids) )
  end

  # GET /missions/:mission_id/squads/:squads_id/crews/new
  def new
    puts(@squad.nil?)
    @crew = @squad.crews.build
  end

  # GET /missions/:mission_id/squads/:squads_id/crews/1/edit
  def edit
  end

  # POST /missions/:mission_id/squads/:squads_id/crews or /missions/:mission_id/squads/:squads_id/crews.json
  def create
    @crew = @squad.crews.build(crew_params)

    respond_to do |format|
      if @crew.save
        # puts params.inspect
        format.html { redirect_to [@mission, @squad, @crew], notice: "Crew was successfully created." }
        format.json { render :show, status: :created, location: [@mission, @squad, @crew] }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @crew.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /missions/:mission_id/squads/:squads_id/crews/1 or /missions/:mission_id/squads/:squads_id/crews/1.json
  def update
    respond_to do |format|
      if @crew.update(crew_params)
        format.html { redirect_to [@mission, @squad, @crew], notice: "Crew was successfully updated." }
        format.json { render :show, status: :ok, location: [@mission, @squad, @crew] }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @crew.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /missions/:mission_id/squads/:squads_id/crews/1 or /missions/:mission_id/squads/:squads_id/crews/1.json
  def destroy
    @crew.destroy
    respond_to do |format|
      format.html { redirect_to mission_squad_crews_url(@mission, @squad), notice: "Crew was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_mission
      if params[:mission_id].to_i.in?(current_user.missions.ids) || current_user.admin?
        @mission = Mission.find_by(id: params[:mission_id])
        render "static_pages/error404", status: :not_found if @mission.nil?
      end
    end
  
    def set_squad
      if @mission.nil? 
        render "static_pages/error404", status: :not_found 
      else
        @squad = @mission.squads.find_by(id: params[:squad_id])
      end
    end
    
    def set_crew
      if @squad.nil? 
        render "static_pages/error404", status: :not_found if @crew.nil?
      else
        @crew = @squad.crews.find_by(id: params[:id])
        render "static_pages/error404", status: :not_found  unless !@crew.nil?
      end
    end

    # Only allow a list of trusted parameters through.
    def crew_params
      params.require(:crew).permit(
        :name,
        :ship_id,
        droid_ids: [],
        rebel_ids: [],
        passenger_ids: []
      )
    end
end

app/helpers/crews_helper.rb
module CrewsHelper
end

app/views/crews/_crew_list.html.erb
<div class="table-responsive">
  <table class="table align-middle">
    <thead>
      <tr>
        <th>Name    </th>
        <th>Ship    </th>
        <th>Droids  </th>
        <th>Actions </th>
      </tr>
    </thead>

    <tbody>
      <% crews.each do |crew| %>
        <tr>
          <td><%= crew.name %></td>
          <td>
            <%= crew.ship.name %>
          </td>
          
          <td>
            <%= crew.droids.pluck(:name).join(', ') %>
          </td>


          <td>
              <%= link_to 'Show', [mission, squad, crew]  %> 
              <% if current_user.admin? %>
                <span>  |  </span>
                <%= link_to 'Edit', edit_mission_squad_crew_path(mission, squad, crew) %> <span>  |  </span>
                <%= link_to 'Destroy', [mission, squad, crew], method: :delete, data: { confirm: 'Are you sure?' } %> 
              <% end %>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/crews/_form.html.erb
<% if crew.errors.any? %>
  <div class="alert alert-danger" role="alert">
    <div class="card-body">
      <h5><%= pluralize(crew.errors.count, "error") %> 
      prohibited this crew from being saved:</h5>

      <ul>
        <% crew.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  </div>
<% end %>


<%= form_with(model: [@mission, @squad, crew]) do |form| %>
  
  <div class="container">
    <div class="row">
      <small class="form-text text-muted">
        Use Ctrl/Cmd or Shift to select multiple Droids, Rebels and Passengers for this Crew
      </small>
    </div>
    </br>

    <div class="row">
      <div class="form-group">
        <%= form.label :name %>
        <%= form.text_field :name , class: 'form-control' %>
      </div>
    </div>

    <div class="row">

      <div class="col">
        <div class="form-group">
          <label for="ship">Select the ship for this Crew</label>
          <%= form.collection_select :ship_id, Ship.order(:name), :id, :name, 
              {include_blank: false}, {class: 'form-select form-select-sm'} %>
        </div>
      </div>

      <div class="col">
        <div class="form-group">
          <label for="droid">Select Droids: </label>
          <%= form.collection_select :droid_ids, Droid.order(:name), :id, :name, {include_blank: false}, 
            {class: 'form-select form-select-sm',size: '4',:multiple => true }  %>
          
        </div>
      </div>
    </div>

    <div class="row">
      <div class="col form-check">
        <label for="rebels">Select Rebels: </label>
        <%= form.collection_select :rebel_ids, User.order(:name), :id, :name, {include_blank: false}, 
          {class: 'form-select form-select-sm',size: '4',:multiple => true }  %>
      </div>

      <div class="col form-check">
        <label for="rebels">Select Passengers: </label>
        <%= form.collection_select :passenger_ids, User.order(:name), :id, :name, {include_blank: false}, 
          {class: 'form-select form-select-sm', size: '4', :multiple => true }  %>
      </div>
    </div>

    </br>

    <div class="row">
      <div class="col-2">
        <div class="actions">
          <%= form.submit "Submit" , class: 'btn btn-primary' %>
        </div>

        <%= link_to 'Back', mission_squad_crews_path(@mission, @squad) %>
      </div>
      
    </div>

  </div>
  
<% end %>

app/views/crews/edit.html.erb
<div class="col-lg-12 mb-4">
  <div class="card shadow mb-4">
    <div class="card-header py-3">
      <h3 class="m-0 font-weight-bold text-primary">Editing Crew</h3>
    </div>  
    <div class="card-body">        
      <%= render 'form', crew: @crew %>
      <div class="container">
        <%= link_to 'Show', [@mission, @squad, @crew]  %> 
      </div> 
       
    </div>  
  </div>
</div>

app/views/crews/index.html.erb
<div class="col-lg-12 mb-4">

  <%= render 'layouts/notice' %>

  <div class="card shadow mb-4">
    <div class="card-header py-3">
      <h3 class="m-0 font-weight-bold text-primary">
        Crews for <%= link_to "Squad #{@squad.name}", mission_squad_path(@mission, @squad), target: :_blank %>
      </h3>
    </div>

    <div class="card-body">   
      <div class="container">
        <div class="row">
          <small class="form-text text-muted">
            Click "Show" to see all details about Droids, Rebels and Passengers for this Crew
          </small>
        </div>
      </div>
      </br>
      <%= render partial:'crew_list', 
      locals: { mission: @mission, squad: @squad, crews: @crews } %>
      </br>
      </br>      

      <%= link_to 'New Crew', new_mission_squad_crew_path(@mission, @squad) if current_user.admin? %>
    </div>
    
  </div>
</div>

app/views/crews/new.html.erb
<div class="col-lg-12 mb-4">
<div class="card shadow mb-4">
  <div class="card-header py-3">
    <h3 class="m-0 font-weight-bold text-primary">New Crew</h3>
  </div>
  <div class="card-body">
    <%= render 'form', crew: @crew %>
    
  </div>
</div>
</div>

app/views/crews/show.html.erb
<%= render 'layouts/notice' %>

<div class="col-lg-12 mb-4">
  <div class="card shadow mb-4">
    <div class="card-header py-3">
      <h3 class="m-0 font-weight-bold text-primary">Crew</h3>
    </div>

    <div class="card-body">  
      <div class="container">
        <div class="row"> 
          <div class="col">
            <p>
              <strong>Name:</strong>
              <%= @crew.name %>
            </p>
          </div>
          
          <div class="col">  
            <p>   
              <strong>Ship:</strong>
              <%= @crew.ship.name %> 
            </p>              
          </div>

          <div class="col">  
            <p>   
              <strong>Droids:</strong>
              <%= @crew.droids.pluck(:name).join(', ') %>
            </p>              
          </div>

        </div>

        <div class="row"> 
          <div class="col">  
            <p>   
              <strong>Rebels:</strong>
              <%= @crew.rebels.pluck(:name).join(', ') %>
            </p>              
          </div>
        </div>


        <div class="row"> 
          <div class="col">  
            <p>   
              <strong>Passengers:</strong>
              <%= @crew.passengers.pluck(:name).join(', ') %>
            </p>              
          </div>
        </div>
        
        <div> 
          <% if current_user.admin? %>
            <%= link_to 'Edit', edit_mission_squad_crew_path(@mission, @squad, @crew) %> |
          <% end %>
            <%= link_to 'Back', mission_squad_crews_path(@mission, @squad) %>
        </div>

        <div> 
          <%= link_to 'Back to Mission', mission_path(@mission) if current_user.admin? %>
        </div>

        
      </div>

      
    </div>
  </div>
</div>