config/routes.rb
Rails.application.routes.draw do
  resources :missions do
    resources :squads do
      resources :crews
    end
  end
  devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :droids
  resources :ships
  resources :locations
  resources :users, except: [:destroy]
  root to: "missions#index"
  
  get "/error404", to: "static_pages#error404"
  get "/error401", to: "static_pages#error401"
end

app/models/squad.rb
class Squad < ApplicationRecord
  validates :name,  presence: true

  has_many :crews, :dependent => :destroy
  belongs_to :leader, class_name: "User"
  belongs_to :mission

  validates_presence_of :leader
end

app/controllers/squads_controller.rb
class SquadsController < ApplicationController
  before_action :set_mission
  before_action :set_squad, only: %i[ show edit update destroy ]

  # GET /missions/:mission_id/squads or /missions/:mission_id/squads.json
  def index
    if @mission.nil?
      render "static_pages/error404", status: :not_found
    else
      @squads = @mission.squads
    end
  end

  # GET /missions/:mission_id/squads/1 or /missions/:mission_id/squads/1.json
  def show
    render "static_pages/error404", status: :not_found unless current_user && 
    (current_user.admin || @squad.id.in?(@mission.squads.ids) )
  end

  # GET /missions/:mission_id/squads/new
  def new
    @squad = @mission.squads.build
  end

  # GET /missions/:mission_id/squads/1/edit
  def edit
  end

  # POST /missions/:mission_id/squads or /missions/:mission_id/squads.json
  def create
    @squad = @mission.squads.build(squad_params)
    respond_to do |format|
      if @squad.save
        format.html { redirect_to [@mission, @squad], notice: "Squad was successfully created." }
        format.json { render :show, status: :created, location: [@mission, @squad] }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @squad.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /missions/:mission_id/squads/1 or /missions/:mission_id/squads/1.json
  def update
    respond_to do |format|
      if @squad.update(squad_params)
        format.html { redirect_to [@mission, @squad], notice: "Squad was successfully updated." }
        format.json { render :show, status: :ok, location: [@mission, @squad] }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @squad.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /missions/:mission_id/squads/1 or /missions/:mission_id/squads/1.json
  def destroy
    @squad.destroy
    respond_to do |format|
      format.html { redirect_to mission_squads_url(@mission), notice: "Squad was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_mission
      if params[:mission_id].to_i.in?(current_user.missions.ids) || current_user.admin?
        @mission = Mission.find_by(id: params[:mission_id])
        render "static_pages/error404", status: :not_found if @mission.nil?
      end
    end
  
    def set_squad
      if @mission.nil? 
        render "static_pages/error404", status: :not_found
      else
        @squad = @mission.squads.find_by(id: params[:id])
        render "static_pages/error404", status: :not_found unless !@squad.nil?
      end
    end
    
    # Only allow a list of trusted parameters through.
    def squad_params
      params.require(:squad).permit(
        :name,
        :leader_id        
      )
    end
end

app/helpers/squads_helper.rb
module SquadsHelper
end

app/views/squads/_form.html.erb
<% if squad.errors.any? %>
  <div class="alert alert-danger" role="alert">
    <div class="card-body">
      <h5><%= pluralize(squad.errors.count, "error") %>
      prohibited this squad from being saved:</h5>

      <ul>
        <% squad.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  </div>
<% end %>

<%= form_with(model: [@mission, squad]) do |form| %>
  <div class="container">
    <div class="row">
      <small class="form-text text-muted">
        Use Ctrl/Cmd or Shift to select multiple Crews for this Squad
      </small>
    </div>
    </br>

    <div class="row">
      <div class="col">
        <div class="form-group">
          <%= form.label :name %>
          <%= form.text_field :name , class: 'form-control' %>
        </div>
      </div>
      
      <div class="col">
        <div class="form-group">
          <label for="leader">Select the Leader for this Squad </label>
          <%= form.collection_select :leader_id, User.order(:name), :id, :name,
              {include_blank: false}, {class: 'form-select form-select-sm'} %>
        </div>
      </div>
    </div>

    <div class="row">
      <div class="col-2">
        <div class="actions">
          <%= form.submit "Submit" , class: 'btn btn-primary' %>
        </div>

        <%= link_to 'Back', mission_squads_path(@mission) %>
      </div>

    </div>

  </div>
<% end %>

app/views/squads/_squad_list.html.erb
<div class="table-responsive">
  <table class="table align-middle">
    <thead>
      <tr>
        <th>Name    </th>
        <th>Leader    </th>
        <th>Crews  </th>
        <th>Actions </th>
      </tr>
    </thead>

    <tbody>
      <% squads.each do |squad| %>
        <tr>
          <td><%= squad.name %></td>
          <td>
            <%= squad.leader.name %>
          </td>

          <td>
            <%= squad.crews.pluck(:name).join(', ') %>
          </td>


          <td>
              <%= link_to 'Show', [mission, squad] %> 
              <% if current_user.admin? %>
                <span>  |  </span>
                <%= link_to 'Edit', edit_mission_squad_path(mission, squad) %> <span>  |  </span>
                <%= link_to 'Destroy', [mission, squad], method: :delete, data: { confirm: 'Are you sure?' } %>
              <% end %>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/squads/edit.html.erb
<div class="col-lg-12 mb-4">
  <div class="card shadow mb-4">
    <div class="card-header py-3">
      <h3 class="m-0 font-weight-bold text-primary">Editing Squad</h3>
    </div>
    <div class="card-body">
      <%= render 'form', squad: @squad %>
      <div class="container">
        <%= link_to 'Show', [@mission, @squad] %>
      </div>

    </div>
  </div>
</div>

app/views/squads/index.html.erb
<div class="col-lg-12 mb-4">

  <%= render 'layouts/notice' %>

  <div class="card shadow mb-4">
    <div class="card-header py-3">
      <h3 class="m-0 font-weight-bold text-primary">
        Squads for <%= link_to "Mission #{@mission.id}", @mission, target: :_blank %>
      </h3>
      <h5>With details: <%= @mission.details %></h5>
    </div>

    <div class="card-body">
      <div class="container">
        <small class="form-text text-muted">
          Click "Show" to see all details about the Leader and the Crews for this Squad
        </small>
      </div>
      </br>

      <%= render partial: 'squad_list',
                 locals: { squads: @squads, mission: @mission } %>

      <br>

      <%= link_to 'New Squad', new_mission_squad_path(@mission) if current_user.admin? %>
    </div>

  </div>
</div>

app/views/squads/new.html.erb
<div class="col-lg-12 mb-4">
<div class="card shadow mb-4">
  <div class="card-header py-3">
    <h3 class="m-0 font-weight-bold text-primary">New Squad for Mission <%= @mission.id %></h3>
  </div>
  <div class="card-body">
    <%= render 'form', squad: @squad %>

  </div>
</div>
</div>

app/views/squads/show.html.erb
<%= render 'layouts/notice' %>

<div class="col-lg-12 mb-4">
  <div class="card shadow mb-4">
    <div class="card-header py-3">
      <h3 class="m-0 font-weight-bold text-primary">Squad</h3>
    </div>

    <div class="card-body">
      <div class="container">
        <div class="row">
          <div class="col">
            <p>
              <strong>Name:</strong>
              <%= @squad.name %>
            </p>
          </div>

          <div class="col">
            <p>
              <strong>Leader:</strong>
              <%= @squad.leader.name %>
            </p>
          </div>

        </div>

        
        <div class="row">
          <strong>Crews </strong>

          <%= render partial:'crews/crew_list', 
          locals: { mission: @mission, squad: @squad, crews: @squad.crews } %>

        </div>

        <div class="row">
          <div class="col-md-12 text-right">
            <%= link_to 'Add Crew', new_mission_squad_crew_path(@mission, @squad), 
                                    class: 'btn btn-primary' if current_user.admin? %>
          </div>
        </div>

        <div>
          <% if current_user.admin? %>
            <%= link_to 'Edit', edit_mission_squad_path(@mission, @squad) %> |
          <% end %>
          <%= link_to 'Back', mission_squads_path(@mission) %>
        </div>

      </div>


    </div>
  </div>
</div>