config/routes.rb
Rails.application.routes.draw do
  resources :missions do
    resources :squads do
      resources :crews
    end
  end
  devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :droids
  resources :ships
  resources :locations
  resources :users, except: [:destroy]
  root to: "missions#index"
  
  get "/error404", to: "static_pages#error404"
  get "/error401", to: "static_pages#error401"
end

app/models/mission.rb
class Mission < ApplicationRecord
  belongs_to :commander, class_name: "User"
  belongs_to :location
  enum status: [ :planning, :in_progress, :success , :failure ]

  has_many :squads, :dependent => :destroy

  validates :start_date, :end_date, :status, :commander_id, :location_id,  presence: true
  
end

app/controllers/missions_controller.rb
class MissionsController < ApplicationController
  before_action :set_mission, only: %i[ show edit update destroy ]

  # GET /missions or /missions.json
  def index
    if current_user.admin?
      @missions = Mission.all
    else
      @missions = current_user.missions
    end
  end

  # GET /missions/1 or /missions/1.json
  def show
    render "static_pages/error404", status: :not_found unless current_user && 
    (current_user.admin || @mission.commander == current_user )
  end

  # GET /missions/new
  def new
    @mission = Mission.new
  end

  # GET /missions/1/edit
  def edit
  end

  # POST /missions or /missions.json
  def create
    @mission = Mission.new(mission_params)
    respond_to do |format|
      if @mission.save
        format.html { redirect_to @mission, notice: "Mission was successfully created." }
        format.json { render :show, status: :created, location: @mission }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @mission.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /missions/1 or /missions/1.json
  def update
    respond_to do |format|
      if @mission.update(mission_params)
        format.html { redirect_to @mission, notice: "Mission was successfully updated." }
        format.json { render :show, status: :ok, location: @mission }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @mission.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /missions/1 or /missions/1.json
  def destroy
    @mission.destroy
    respond_to do |format|
      format.html { redirect_to missions_url, notice: "Mission was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_mission
      @mission = Mission.find_by(id: params[:id])
      render "static_pages/error404", status: :not_found if @mission.nil?
    end

    # Only allow a list of trusted parameters through.
    def mission_params
      params.require(:mission).permit(
        :start_date,
        :end_date,
        :details,
        :status,
        :commander_id,
        :location_id
      )
    end
end

app/helpers/missions_helper.rb
module MissionsHelper
end

app/views/missions/_form.html.erb
<% if mission.errors.any? %>
  <div class="alert alert-danger" role="alert">
    <div class="card-body">
      <h5>
      <%= pluralize(mission.errors.count, "error") %>
      prohibited this mission from being saved: </h5>

      <ul>
        <% mission.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  </div>
<% end %>

<%= form_with(model: mission) do |form| %>
  <div class="container">
    </br>

    <div class="row">
      <div class="col">
        <label for="commander">Select the Commander for this Mission: </label>
        <%= form.collection_select :commander_id, User.order(:name), :id, :name,
            {include_blank: false}, {class: 'form-select form-select'} %>
      </div>

      <div class="col">
        <label for="location">Select the Location: </label>
        <%= form.collection_select :location_id, Location.order(:system), :id, :system,
            {include_blank: false}, {class: 'form-select form-select'} %>
      </div>

    </div>

    </br>

    <div class="form-group row">

      <div class="col">
        <div class="form-group">
          <%= form.label :start_date %>
          <%= form.date_select :start_date ,{include_blank: false}, {class: 'form-select-sm'} %>
        </div>
      </div>

      <div class="col">
        <div class="form-group">
          <%= form.label :end_date %>
          <%= form.date_select :end_date ,{include_blank: false}, {class: 'form-select-sm'} %>
        </div>
      </div>


    </div>

    <div class="row">
      <div class="col">
        <div class="form-group">
          <%= form.label :details %>
          <%= form.text_area :details , class: 'form-control' %>
        </div>
      </div>

      <div class="col">
        <div class="form-group">
          <%= form.label :status %>
          <%= form.select :status, Mission.statuses.keys.map{ |key| [key.humanize, key] }, {}, class:'form-select' %>
        </div>
      </div>
    </div>

    <div class="row">
      <div class="col-2">
        <div class="actions">
          <%= form.submit "Submit" , class: 'btn btn-primary' %>
        </div>

      </div>

    </div>

  </div>
<% end %>

app/views/missions/edit.html.erb
<div class="col-lg-12 mb-4">
  <div class="card shadow mb-4">
    <div class="card-header py-3">
      <h3 class="m-0 font-weight-bold text-primary">Editing Mission</h3>
    </div>  
    <div class="card-body">        
      <%= render 'form', mission: @mission %>
      <div class="container">
        <%= link_to 'Show', @mission %>
      </div> 
       
    </div>  
  </div>
</div>

app/views/missions/index.html.erb
<div class="col-lg-12 mb-4">

  <%= render 'layouts/notice' %>

  <div class="card shadow mb-4">
    <div class="card-header py-3">
      <h3 class="m-0 font-weight-bold text-primary">Missions</h3>
    </div>
    
    <div class="card-body">   
      <div class="container">
        <small class="form-text text-muted">
          Click "Show" to see all the details for this Mission
        </small>
      </div>
      </br>
      <div class="table-responsive">
        <table class="table align-middle">
          <thead>
            <tr>
              <th>Start date</th>
              <th>End date</th>
              <th>Status</th>
              <th>Commander</th>
              <th>Actions </th>
            </tr>
          </thead>

          <tbody>
            <% @missions.each do |mission| %>
              <tr>
                <td><%= mission.start_date %></td>
                <td><%= mission.end_date %></td>
                <td><%= mission.status.humanize %></td>
                <td><%= mission.commander.nil? ? "No commander assigned" : mission.commander.name %></td>

                <td>
                    <%= link_to 'Show', mission %> 
                    <% if current_user.admin? %>
                      <span>  |  </span>
                      <%= link_to 'Edit', edit_mission_path(mission) %> <span>  |  </span>
                      <%= link_to 'Destroy', mission, method: :delete, data: { confirm: 'Are you sure?' } %>
                    <% end %>
                </td>
              </tr>
            <% end %>            
            
          </tbody>
        </table>
      </div>
    
      <br>

      <%= link_to 'New Mission', new_mission_path if current_user.admin? %>
    </div>

  </div>
</div>

app/views/missions/new.html.erb
<div class="col-lg-12 mb-4">
<div class="card shadow mb-4">
  <div class="card-header py-3">
    <h3 class="m-0 font-weight-bold text-primary">New Mission</h3>
  </div>
  <div class="card-body">
    <%= render 'form', mission: @mission %>
    
  </div>
</div>
</div>

app/views/missions/show.html.erb
<%= render 'layouts/notice' %>

<div class="col-lg-12 mb-4">
  <div class="card shadow mb-4">
    <div class="card-header py-3">
      <h3 class="m-0 font-weight-bold text-primary">Mission</h3>
    </div>

    <div class="card-body">
      <div class="container">
        <div class="row">
          <div class="col">
            <p>
              <strong>Commander:</strong>
              <%= @mission.commander.nil? ? "No commander assigned" : @mission.commander.name %>
            </p>
          </div>
          <div class="col">
            <p>
              <strong>Location:</strong>
              <%= @mission.location.system %>
            </p>
          </div>

          <div class="col">
            <p>
              <strong>Status:</strong>
              <%= @mission.status.humanize %>
            </p>
          </div>
        </div>



        <div class="row">
          <p>
            <strong>Start date:</strong>
            <%= @mission.start_date %>
          </p>
          <p>
            <strong>End date:</strong>
            <%= @mission.end_date %>
          </p>
        </div>

        <div class="row">
          <p>
            <strong>Details:</strong>
            <%= @mission.details %>
          </p>
        </div>

        </br>

        <div class="row">
          <strong>Squads</strong>
          <%= render partial: 'squads/squad_list',
                     locals: { squads: @mission.squads, mission: @mission } %>

        </br>

        <div class="row">
          <div class="col-md-12 text-right">
            <%= link_to 'Add Squad', new_mission_squad_path(@mission), class: 'btn btn-primary' if current_user.admin? %>
          </div>
        </div>

        </br>

        <div>
          <% if current_user.admin? %>
            <%= link_to 'Edit', edit_mission_path(@mission) %> |
          <% end %>
          <%= link_to 'Back', missions_path %>
        </div>

      </div>


    </div>
  </div>
</div>