config/routes.rb
Rails.application.routes.draw do
  resources :missions do
    resources :squads do
      resources :crews
    end
  end
  devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :droids
  resources :ships
  resources :locations
  resources :users, except: [:destroy]
  root to: "missions#index"
  
  get "/error404", to: "static_pages#error404"
  get "/error401", to: "static_pages#error401"
end

app/views/layouts/_footer.html.erb
<footer class="sticky-footer bg-white">
  <div class="container my-auto">
    <div class="copyright text-center my-auto">
        <span>Copyright &copy; StarWars MIS 2021</span>
    </div>
  </div>
</footer>
<!-- End of Footer -->

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-expand navbar-light bg-white topbar mb-4 static-top shadow">
  <div class="navbar-nav ml-auto">
    
    <% if user_signed_in? %>

        <div class="btn-group dropstart" >
          <!-- Sidebar Toggle (Topbar) -->
          <button class="btn dropdown-toggle" type="button" id="dropdownMenu2" data-bs-toggle="dropdown"
           data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            <i class="bi bi-person-circle"></i>
            <span class="mr-2 d-none d-lg-inline text-gray-600 small">
              <%= current_user.name %>
            </span>
          </button>

          <div class="dropdown-menu" aria-labelledby="dropdownMenu2">

            <button class="dropdown-item" type="button">
            <i class="bi bi-gear"></i>
              Profile settings
            </button>

            <button class="dropdown-item" type="button">
              <i class="bi bi-arrow-right-circle"></i>
              <%= link_to "Sign out", destroy_user_session_path, method: :delete %>
            </button>
          </div>

        </div>
      
    <% else %>
      <div class="text-center">
        <%= link_to 'Register', new_user_registration_path %> or <%= link_to 'Sign in', new_user_session_path %>
      </div>
    <% end %>
  </div>  
</nav>
<!-- End of Navbar -->

app/views/layouts/_notice.html.erb
<% if !notice.blank? %>
<div class="alert alert-primary" role="alert">
    <div class="card-body">
      <%= notice %> 
      <p class="alert"><%= alert %></p>
    </div>
  </div>
<% end %>

app/views/layouts/_sidebar.html.erb
<ul class="navbar-nav bg-gradient-primary sidebar sidebar-dark accordion" id="accordionSidebar">

  <!-- Sidebar - Brand -->
  <a class="sidebar-brand d-flex align-items-center justify-content-center" href="<% root_path %>">
    <div class="sidebar-brand-icon rotate-n-15">
    <i class="bi bi-stars"></i>
    </div>
    <div class="sidebar-brand-text mx-3">Star Wars MIS </div>
  </a>
  <!-- Divider -->
  <hr class="sidebar-divider my-0">
  
  <!-- Nav Item - Dashboard -->
  <li class="nav-item active">
    <a class="nav-link" href="<% root_path %>">
      <i class="bi bi-speedometer2"></i>
      <span>Dashboard</span>
    </a>
  </li>
  
  <% if current_user.admin? %>
    <!-- Divider -->
    <hr class="sidebar-divider">
    <!-- Heading -->
    <div class="sidebar-heading">
        Users
    </div>
    <!-- Nav Item - Pages Collapse Menu -->
    <li class="nav-item">
      <a class="nav-link collapsed" href="/users" data-toggle="collapse" data-target="#collapseTwo"
        aria-expanded="true" aria-controls="collapseTwo">
        <i class="bi bi-person-circle"></i>
        <span>Users</span>
      </a>
    </li>
  <% end %>

  <!-- Divider -->
  <hr class="sidebar-divider">
  <!-- Heading -->
  <div class="sidebar-heading">
    Missions
  </div>
  <!-- Nav Item - Pages Collapse Menu -->
  <li class="nav-item">
    <div>
      <%= link_to "Missions", missions_path , class: 'nav-link collapsed'  %>
    </div>

  </li>

  <!-- Nav Item - Pages Collapse Menu -->
  <li class="nav-item">
    <div>
      <%= link_to "Ships", ships_path , class: 'nav-link collapsed'  %>
    </div>
  </li>

  <!-- Nav Item - Pages Collapse Menu -->
  <li class="nav-item">
    <div>
      <%= link_to "Droids", droids_path , class: 'nav-link collapsed'  %>
    </div>
  </li>
  <!-- Nav Item - Pages Collapse Menu -->
  <li class="nav-item">
    <div>
      <%= link_to "Locations", locations_path , class: 'nav-link collapsed'  %>
    </div>
  </li>


</ul>
<!-- End of Sidebar -->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <title>StarWarsMIS</title>

    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link
        href="https://fonts.googleapis.com/css?family=Nunito:200,200i,300,300i,400,400i,600,600i,700,700i,800,800i,900,900i"
        rel="stylesheet">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.5.0/font/bootstrap-icons.css">
    
    
  </head>
  <body id="page-top">
    <!-- Page Wrapper -->
    <div id="wrapper">
      <!-- Sidebar -->
      <%= render 'layouts/sidebar' %>                
        <!-- Content Wrapper -->
        <div id="content-wrapper" class="d-flex flex-column">
            
            <!-- Main Content -->
            <div id="content">       
              <!-- navbar -->
              <%= render 'layouts/navbar' %> 
              <!-- Begin Page Content -->
              <div class="container-fluid">

                <!-- statistics (maybe) -->
                 
                <!-- Content Row -->
                <div class="row">
                
                    <%= yield %>                            
                </div>

              </div>

            </div>
            <!-- End of Main Content -->

            <!-- Footer -->
            <%= render 'layouts/footer' %>
               
        </div>
          <!-- End of Content Wrapper -->  
    </div>
    <!-- End of Page Wrapper -->
  </body>
</html>

app/views/layouts/public.html.erb
<!DOCTYPE html>
<html lang="en">

  <head>

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <title>StarWarsMIS</title>

    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link
        href="https://fonts.googleapis.com/css?family=Nunito:200,200i,300,300i,400,400i,600,600i,700,700i,800,800i,900,900i"
        rel="stylesheet">

  </head>
  <body class="bg-image">
    <div class="container">

      <!-- Outer Row -->
      <div class="row justify-content-center">
        <div class="col-xl-10 col-lg-12 col-md-9">
          <div class="card o-hidden border-0 shadow-lg my-5">
            <div class="card-body p-0">
              <!-- Nested Row within Card Body -->
              <div class="row">
                <div class="col-lg-12">
                  <div class="p-5">

                    <%= yield %>   

                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>

    </div>

  </body>

</html>